#!/bin/bash

# Mounts a Turnigy 9XR PRO when connected with the bootloader running
# Makes horrible assumptions about the paths of the devices

echo "Mount... "
udisks --mount /dev/sdb1
udisks --mount /dev/sdc
echo "done."
