#!/bin/bash

# Unounts a Turnigy 9XR PRO when connected with the bootloader running
# Makes horrible assumptions about the paths of the devices

echo -n "Sync... "
sync
echo "done."

echo "Unmount... "
udisks --unmount /dev/sdb1
udisks --unmount /dev/sdc
echo "done."
