#!/bin/bash

# Unounts a Turnigy 9XR PRO when connected with the bootloader running
# Makes horrible assumptions about the paths of the devices

echo -n "Sync... "
sync
echo "done."

echo "Unmount... "
udisksctl unmount -b /dev/sdb1
udisksctl unmount -b /dev/sdc
echo "done."
